baseURL = 'https://jabeztho.com/'
languageCode = 'en-us'
title = 'Jabez Tho'
disableKinds = ["taxonomy","taxonomyTerm"]
googleAnalytics = 'G-6DH827VXED'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = "node_modules/pdfobject/pdfobject.min.js"
    target = "static/js/pdfobject.min.js"



